### ISSUE TITLE
Mechanism for installing additional updates from pip

### ISSUE THREAD

**Issue by CRImier** [ZeroPhone/ZPUI#34]
Today, I'm merging a PR that requires the system to have one more Python module installed through pip (namely, `vobject`). Latest SD card image, though, doesn't have it available, so if a user will update ZPUI through git (the only update mechanism available for now), they'll lack the package and the part of ZPUI that requires this package will no longer work. In this case, it's an app, so it'll just fail to load and ZPUI will continue working - but it's still a 2-second message shown to the user during bootup which blocks the bootup, not too user-friendly. That's not the only problem:
1. Actually solving the problem (installing the module using `pip install`) will require user's manual intervention, not only having to log in through SSH and install the library, but also figure out which library needs to be installed.
2. Some crucial app might stop working if made depend on some not-yet-installed library (of course, adding hard dependencies has to be thought out by the developer if an app already has users relying on it, but it's a problem nevertheless)
3. In case with core ZPUI subsystems, as well as drivers, this might make ZPUI inaccessible from the user, which is a bad thing to do.

For now, I'm likely going to make a helper for this [(based on this SO question)](https://stackoverflow.com/questions/12332975/installing-python-module-within-code), with install instructions, then test it and roll it out to users. However, is this the proper solution to this problem? For example, once this helper is used in the module, it's going to have to remain there (since there are going to be users not updating ZPUI until after the helper is removed), unless some other solution is found.

**Comment by monsieurh** [comment]
Thanks for raising the issue.

Since the update mechanism is git based at the moment, I'd recommend *not* adding a second layer (a.k.a. using `pip` in ZPUI itself). It would confuse maintainers (two place to read the update code) and add a dangerous dependency. (How do you update ZPUI using ZPUI if you broke it?)

I would recommend updating the `update.sh` script instead, and optionnaly putting a `post-update` git hook.  

The good practice for `PyPy` dependencies is having a file called `requirements.txt` at the root of the project.

So the script would:
1. Pull the git repo
2. run `pip install -r requirements.txt`
3. run tests
4. copy to installation folder
If any point fails, return or prompt the user to ask if we need to continue.

**Comment by monsieurh** [comment]
see #35 for a concrete proposition/implementation

**Comment by CRImier** [comment]
Your proposed update process, together with the changes I'm suggesting, will allow seamless installation of dependencies during both CLI and UI update processes, so once #35 is merged, the issue will be solved =)

**Comment by CRImier** [comment]
Speaking about updating ZPUI while running ZPUI - I completely agree. However, 1) it's the only viable option so far - we can't have users logging through SSH just to update the UI 2) we do, in fact, need to add safeguards to the update app to make sure that ZPUI can be successfully launched again, and your proposition with running tests helps with that goal a lot.

**Comment by CRImier** [comment]
This issue will no longer be solved the way that's described in the title&first comment, so, solved for now =)

**Comment by CRImier** [comment]
That is, the problem described is now solved by the new update mechanism, which is discussed in other issues&PRs
